#!/bin/bash
if [ $# -eq 0 ] || [ -z "$1" ] || [ -z "$2" ]
  then
    echo "No arguments supplied"
    echo "Usage: search-nuclei $folder $query"
fi
cd "$1"
for i in $(ls -d */);
do
domain=$(echo $i | cut -d "/" -f1)
cd $i
if [[ ! -f httpx-$domain.canary ]]
then
        continue
else
        echo $domain
        cat httpx-$domain.txt | grep "$2"
fi
cd ..
done